"use client";
import { FormEvent, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";

const choices = ["Ware yams", "Seed yams", "Goats", "Breeding stock", "Organic manure", "Advisory service", "Partnership", "Other"];
export function EnquiryForm() {
  const params = useSearchParams(); const [state, setState] = useState<"idle" | "sending" | "success" | "error">("idle");
  const [type, setType] = useState("Ware yams"); useEffect(() => { const value = params.get("type"); if (value && choices.includes(value)) setType(value); }, [params]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setState("sending"); const form = event.currentTarget; const payload = Object.fromEntries(new FormData(form)); try { const result = await fetch("/api/enquiry", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); if (!result.ok) throw new Error(); setState("success"); form.reset(); setType("Ware yams"); } catch { setState("error"); } }
  if (state === "success") return <div className="border-l-4 border-[#326043] bg-[#eaf0e5] p-6" role="status"><h2 className="display text-3xl font-bold text-[#173d2e]">Thank you—your enquiry has been received.</h2><p className="mt-3 leading-7 text-[#526258]">We will respond as soon as possible with availability or the next steps.</p><button className="mt-5 text-sm font-bold underline" onClick={() => setState("idle")}>Send another enquiry</button></div>;
  return <form className="grid gap-5" onSubmit={submit}><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">Full name *<input className="field" name="name" required autoComplete="name" /></label><label className="text-sm font-bold">Email address *<input className="field" name="email" required type="email" autoComplete="email" /></label><label className="text-sm font-bold">Phone / WhatsApp<input className="field" name="phone" type="tel" autoComplete="tel" /></label><label className="text-sm font-bold">Organisation or business name<input className="field" name="organisation" autoComplete="organization" /></label><label className="text-sm font-bold">Enquiry type *<select className="field" name="type" required value={type} onChange={e => setType(e.target.value)}>{choices.map(choice => <option key={choice}>{choice}</option>)}</select></label><label className="text-sm font-bold">Quantity or farm size<input className="field" name="quantity" /></label><label className="text-sm font-bold">Preferred fulfilment<select className="field" name="fulfilment"><option>Bulk</option><option>Retail</option><option>Delivery discussion</option><option>Pickup discussion</option></select></label><label className="text-sm font-bold">Location (town/state)<input className="field" name="location" autoComplete="address-level2" /></label></div><label className="text-sm font-bold">How can we help? *<textarea className="field min-h-35 resize-y" name="message" required /></label><input className="hidden" name="website" tabIndex={-1} autoComplete="off" /><label className="flex items-start gap-3 text-sm leading-6"><input className="mt-1 size-4" name="consent" required type="checkbox" />I agree that Roots & Hooves Agro Farms may use my details to respond to this enquiry. *</label>{state === "error" && <p className="text-sm font-bold text-red-700" role="alert">We could not send your enquiry. Please try again or email Abolmike@gmail.com.</p>}<button className="button w-fit disabled:opacity-60" disabled={state === "sending"}>{state === "sending" ? "Sending…" : "Send enquiry"}</button></form>
}
